apiVersion: v1
kind: Service
metadata:
  name: {{ include "hooklane.fullname" . }}-mock-sink
  labels:
    {{- include "hooklane.labels" . | nindent 4 }}
    app.kubernetes.io/component: mock-sink
spec:
  selector:
    {{- include "hooklane.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mock-sink
  ports:
    - name: http
      port: {{ .Values.mockSink.service.port }}
      targetPort: http
