{{- if .Values.observability.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hooklane.fullname" . }}-prometheus
  labels:
    {{- include "hooklane.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: ClusterIP
  selector:
    {{- include "hooklane.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
  ports:
    - name: http
      port: {{ .Values.observability.prometheus.service.port }}
      targetPort: http
{{- end }}
