{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hooklane.fullname" . }}-placeholder
  labels:
    {{- include "hooklane.labels" . | nindent 4 }}
type: Opaque
data: {}
{{- end }}
